# ── Remove the obsolete “version:” key ──
services:
  db:
    image: postgres:15-alpine    # slimmer official image; no need to maintain a Dockerfile
    container_name: postgresql-db
    restart: unless-stopped      # more precise than “always”
    ports:
      - "5432:5432"
    environment:
      # load creds from an .env file (see next)
      POSTGRES_USER:      ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      POSTGRES_DB:        ${POSTGRES_DB}
      PGDATA:             /var/lib/postgresql/data/pgdata  # explicit data dir
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local